
[package]
name = "server"
version = "0.1.0"
edition = "2021"
[dependencies]
tokio = { version = "1", features = ["full"] }
rustls = "=0.23.19"
rustls-pemfile = "1.0"
tokio-rustls = "=0.26.1"
native-tls = "0.2"
tokio-native-tls = "0.3"
base64 = "0.13"
dotenv = "0.15.0"